name: ci_test
on:
  push:
    branches: 
      - 'test_action_feature**'
jobs:
  pruebas_feature:
    name: Pruebas en rama feature
    runs-on: ubuntu-latest
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v2
    - name: Configuración de entorno de python
      uses: actions/setup-python@v2
      with:
          python-version: '3.7'
    - name: Instalación de librerías y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Correr pruebas
      id: correr-pruebas
      run: python -m unittest discover -s tests -v
    - name: Cálculo de cubrimiento
      id: cubrimiento
      run: |
          coverage run -m unittest discover -s tests -v
          coverage report -m
  automerge_develop:
    name: Automerge con rama develop
    needs: pruebas_feature
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: test_action_develop
          target-branch: ${{ github.ref }}